### ISSUE TITLE
NA-s and more

### ISSUE THREAD

**Issue by thoree** [magnusdv/ribd#1]
I've started trying ribd - great stuff!
When I run  the following example in the man file

library(pedtools)
x = fullSibMating(2)
x_brothers = swapSex(x, 6)
ibd_identity_x(x_brothers, ids = 5:6)

I don't get the NA-s entries  announced under Value in the documentation.
A simillar comment applies to male-female pairs.
 **Later**: I think I managed to find a problem:

x = halfSibStack(2)
ibd_identity(x, ids = c(4,5))

**Comment by magnusdv** [comment]
Ok, I think it makes sense to return irrelevant coefficients as NA (as stated in the docs) instead of 0. This should be fixed now.

The second problem seems to be a legitimate bug. Could you open a separate issue for this, please? Thanks.
