### ISSUE TITLE
Shorter kinship lines

### ISSUE THREAD

**Issue by hildekb** [magnusdv/ribd#11]
Implementation of shorter kinship lines, e.g. restricted to the triangle itself, when using ibdTriangle() would be great!

**Comment by hildekb** [comment]
Maybe the following lines of code can substitute the for-loop that creates the kinship lines in ibdTrinagle()? In my code suggestion, abline() is substituted with segments() and I changed the lable position a bit. 

for (phi in kinshipLines) {
  if (phi < 0 || phi > 0.5)
    stop2("kinship coefficient not in intervall [0, 0.5]", phi)
  
  if (phi>1/4){
      segments(x0 =0,y0 = 4*phi-1,x1 = 1-2*phi,y1 = 2*phi, lty = 2)
    } else{
      segments(x0 = 1-4*phi,y0 = 0,x1 = 1-2*phi,y1 = 2*phi, lty = 2)
    }
  labpos.x = 1-2*phi
  labpos.y = 2*phi
  lab = substitute(paste(phi1, " = ", a), list(a = phi))
  text(labpos.x, labpos.y, labels = lab, pos = 4, srt = 45)
}

**Comment by hildekb** [comment]
Maybe the following lines of code can substitute the for-loop that creates the kinship lines in ibdTrinagle()? In my code suggestion, abline() is substituted with segments() and I changed the lable position a bit.


``` r
library(ribd)
#> Loading required package: pedtools
kinshipLines = c(0.3,1/4,1/8,1/16)
ibdTriangle()
for (phi in kinshipLines) {
  if (phi < 0 || phi > 0.5)
    stop2("kinship coefficient not in intervall [0, 0.5]", phi)
  
  if (phi>1/4){
      segments(x0 =0,y0 = 4*phi-1,x1 = 1-2*phi,y1 = 2*phi, lty = 2)
    } else{
      segments(x0 = 1-4*phi,y0 = 0,x1 = 1-2*phi,y1 = 2*phi, lty = 2)
    }
  labpos.x = 1-2*phi
  labpos.y = 2*phi
  lab = substitute(paste(phi1, " = ", a), list(a = phi))
  text(labpos.x, labpos.y, labels = lab, pos = 4, srt = 45)
}
```

![](https://i.imgur.com/rXrWB6R.png)

<sup>Created on 2021-03-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by magnusdv** [comment]
This looks great! 

Would you care to prepare a PR for this? (Otherwise I'll do it myself, but it may take a while.)
Preferably with a parameter `interiorLines` enabling you to choose between the current behaviour and yours.

If you are new to PR's, I strongly recommend checking out the new functionality of the `usethis` package - makes everyting a breeze.
