### ISSUE TITLE
`ibd_inbreeding` and founders

### ISSUE THREAD

**Issue by thoree** [magnusdv/ribd#3]
I wonder if the inbreeding coefficient of individual 1 below should be 1:
``` r
library(ribd)
#> Loading required package: pedtools
x = nuclearPed(1)
founder_inbreeding(x, "1") = 1
ibd_inbreeding(x)
#> 1 2 3 
#> 0 0 0
```

<sup>Created on 2019-01-21 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by magnusdv** [comment]
Thanks!! Fixed now, and tests added...
