### ISSUE TITLE
`twoLocusIdentity()` example suggested

### ISSUE THREAD

**Issue by thoree** [magnusdv/ribd#8]
Here's an example that runs nicely:

``` r
library(ribd, quietly = TRUE)
#> 
#> Attaching package: 'ribd'
#> The following object is masked from 'package:base':
#> 
#>     kappa
x1 = halfCousinPed(1)
j2.1 = twoLocusIdentity(x1, ids = leaves(x1), rho = 0.25)
x2 = halfCousinPed(0, removal = 2)
j2.2 = twoLocusIdentity(x2, ids = leaves(x2), rho = 0.25)
stopifnot(all(j2.1 == j2.2))
```

<sup>Created on 2019-09-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by magnusdv** [comment]
Very nice - in the spirit of Donnelly ('83).

PS: These are non-inbred relationships, though, so one might argue that it is a bit of an overkill to use `twoLocusIdentity()` here. The simpler `twoLocusIBD()` suffices.

**Comment by magnusdv** [comment]
Added to `twoLocusIBD()`docs now: 71f9881
